id: I1B2E9C92
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W3CN1694
  ocr_info:
    timestamp: 03/21/23T14:11:55
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-28 22:40:18.090140+00:00
last_modified: 2024-02-28 22:40:18.090146+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN1694
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN1694
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསོ་རིག་རྒྱུད་བཞི། （ལྕགས་པོ་རིའི་པར་གསར།）
  languages:
  - bo
  author: གཡུ་ཐོག་གསར་མ་ཡོན་ཏན་མགོན་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.841760637731134
  ocr_word_median_confidence_index: 0.91
bases:
  I3CN1696:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN1696
      total_pages: 702
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN1696.txt
    statistics:
      ocr_word_median_confidence_index: 0.91
      ocr_word_mean_confidence_index: 0.841760637731134
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
